from sc_integration.integration_graph import build_integration_graph, build_integration_loss_adj
from sc_integration.integration_DIF import integration_diffusion, integration_high_throughput_mode
from sc_integration.integration_GCN import integration_gcn